#!/bin/sh


cd contrib
dpkg --build erlyvideo
VERSION=`grep Version: erlyvideo/DEBIAN/control | sed -n -e 's/Version: \(.*\)/\1/p'`
mv erlyvideo.deb /apps/erlyvideo/debian/public/binary/erlyvideo_${VERSION}_all.deb
cd /apps/erlyvideo/debian
./update

