#!/bin/bash

Package()
{
echo $1
cd $1
dpkg-scanpackages -m $2 > $2/Packages
cd $2
#dpkg-scansources . > Sources
gzip -9c Packages > Packages.gz
#gzip -c Sources > Sources.gz


echo "Origin: Erlyvideo repositories
Label: Erlyvideo
Archive: stable
Architectures: i386 amd64 all source
Components: net
Suite: $2
Version: 9.10
Description: Erlyvideo streaming server http://erlyvideo.org/
MD5Sum:" > Release

#ls Packages* Sources* Release | while read ln
ls Packages* Release | while read ln
do
md=`md5sum $ln |awk {' print $1 '}`
sz=`du -sb $ln`
echo " $md $sz" >> Release.tmp
done
cat Release.tmp >> Release
rm -f Release.tmp

rm -f Release.gpg
gpg -sbao Release.gpg Release
}

Package /apps/erlyvideo/debian/public $1

