#!/bin/sh

### BEGIN INIT INFO
# Provides:          erlyvideo
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the erlyvideo streaming server
# Description:       starts the erlyvideo using erlang system
### END INIT INFO


case "$1" in
  start)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  stop)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  restart)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  soft-restart)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  upgrade)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  reconfigure)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  reboot)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  ping)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  console)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  attach)
  cd /opt/erlyvideo && ./bin/erlyvideo "$1"
  ;;
  attach-erl)
  cd /opt/erlyvideo && ./erts-5.8.4/bin/erl -name debug@127.0.0.1 -remsh erlyvideo@127.0.0.1
  ;;
  *)
  echo $"Usage: $0 {start|stop|restart|soft-restart|upgrade|reboot|ping|console|attach}"
  exit 1
esac

exit 0
