#!/usr/bin/env escript

main([]) ->
  Root = filename:join(filename:dirname(escript:script_name()), ".."),
  Files1 = lists:map(fun(Path) ->
    {ok, Bin} = file:read_file(Path),
    {filename:basename(Path), Bin}
  end, [Path || Path <- filelib:wildcard(Root ++ "/apps/*/ebin/*"), Path =/= ".gitignore"]),
  
  Files2 = filelib:fold_files("wwwroot", ".*", true, fun(Path, Acc) -> 
    {ok, Bin} = file:read_file(Path),
    [{Path, Bin}|Acc] 
  end, []),

  Files3 = lists:map(fun(Path) ->
    {ok, Bin} = file:read_file(Path),
    {Path, Bin}
  end, filelib:wildcard("scripts/*.ex")),
  

  Files = Files1 ++ Files2 ++ Files3,
  {ok, {"mem", ZipBin}} = zip:create("mem", Files, [memory]),
  Script = <<"#!/usr/bin/env escript\n%%! -noshell -noinput\n", ZipBin/binary>>,
  ok = file:write_file("erlyvideo", Script),
  os:cmd("chmod u+x erlyvideo"),
  halt(0).
  