#!/usr/bin/env ERL_LIBS=apps escript

-include_lib("erlmedia/include/video_frame.hrl").

main([Path]) ->
  {ok, F} = file:open(Path, [binary, read]),
  Offset = flv:data_offset(),
  dump(F, Offset).
  
dump(F, Offset) ->
  case flv:read_frame({file, F}, Offset) of
    #video_frame{next_id = Next} = Frame ->
      dump_frame(Frame),
      dump(F, Next);
    eof ->
      ok
  end.


dump_frame(#video_frame{content = Content, codec = Codec, flavor = Flavor, dts = DTS, body = Body, sound = Sound}) ->
  Info = case Codec of
    _ when Flavor == config -> io_lib:format("~p", [Body]);
    h264 -> io_lib:format("~p bytes", [size(Body)]);
    aac -> io_lib:format("~p", [Sound]);
    _ when Content == metadata -> io_lib:format("~p", [Body])
  end,
    
  io:format("~8.s ~5.s ~9.s ~6.B ~s~n", [Content, Codec, Flavor, round(DTS), Info]).

