#!/usr/bin/env escript
%%! -pa apps/erlyvideo/ebin

main([]) ->
  io:format("~s out.mp4 File1@Track1 File@Track2 .. SpecN~n", [escript:script_name()]),
  erlang:halt(1);


% Логика такая:
% 1. собираем спецификацию файлов
% 2. открываем каждый файл
% 3. идем по нему в sax стиле:   atom(AtomName, Content, Context) -> {ok, Context}
% 4. атомы дорожек перебираем только если нужно по спецификации
% 5. заходя в атом дорожки сохраняем в оригинальном виде все атомы кроме stsc и stco. 
% 6. stsz нужно будет прочитать только на вычитывании содержимого дорожки
% 7. добавляем в выходном файле новую дорожку
% 8. пишем её 

% Т.е. нужны следующие функции:
% 1. parse_atom(Reader, InitialState) -> {ok, State}
% 2. 

main([OutPath|Inputs]) ->  
  mp4mux:run(OutPath, Inputs).
  

















