#!/usr/bin/env escript
%%! 


main([]) ->
  Files = 
  load_files("*", "ebin") ++
  load_files("*", "deps/amf/ebin") ++
  load_files("*", "deps/erlmedia/ebin") ++
  load_files("*", "deps/erlydtl/ebin") ++
  load_files("*", "deps/ibrowse/ebin") ++
  load_files("*", "deps/log4erl/ebin") ++
  load_files("*", "deps/mpegts/ebin") ++
  load_files("*", "deps/rtmp/ebin") ++
  load_files("*", "deps/rtp/ebin") ++
  load_files("*", "deps/rtsp/ebin"),
  {ok, {"mem", ZipBin}} = zip:create("mem", Files, [memory]),
  write_script("erlyvideo", "%%! -name ems -noinput -detached -noshell +A 8 +K true\n", ZipBin),
  write_script("erlyvideo_ctl", "%%! -name ems -shell \n", ZipBin),
  ok.


write_script(Name, Flags, ZipBin) ->
  Script = <<"#!/usr/bin/env escript\n", (list_to_binary(Flags))/binary, ZipBin/binary>>,
  ok = file:write_file(Name, Script),
  os:cmd("chmod u+x "++Name),
  ok.
  
    
load_files(Wildcard, Dir) ->
    [read_file(Filename, Dir) || Filename <- filelib:wildcard(Wildcard, Dir)].

read_file(Filename, Dir) ->
    {ok, Bin} = file:read_file(filename:join(Dir, Filename)),
    {Filename, Bin}.
