#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -name reverse_mpegts -mnesia debug verbose -pa ebin -pa deps


main([FromUrl, ToUrl]) ->
  Root = filename:join(filename:dirname(escript:script_name()), "..")++"/",
  true = code:add_pathz(Root ++ "ebin"),
  true = code:add_pathz(Root ++ "deps/rtmp/ebin"),
  true = code:add_pathz(Root ++ "deps/log4erl/ebin"),
  true = code:add_pathz(Root ++ "deps/amf/ebin"),
  true = code:add_pathz(Root ++ "deps/erlmedia/ebin"),
  ems_log:start(),
  reverse_mpegts:loop(FromUrl, ToUrl);
  
main(_) ->
  io:format("http://[source.url/stream.ts] http://[erlyvideo.url]/stream/[name].ts ~n").

  
