#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -name reverse_mpegts


main([FromUrl, ToUrl]) ->
  Root = filename:join(filename:dirname(escript:script_name()), ".."),
  [code:add_pathz(Path) || Path <- filelib:wildcard(Root ++ "/apps/*/ebin")],
  ems_log:start(),
  reverse_mpegts:loop(FromUrl, ToUrl);
  
main(_) ->
  io:format("http://[source.url/stream.ts] http://[erlyvideo.url]/stream/[name].ts ~n").

  
