#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -name reverse_mpegts -mnesia debug verbose


main([FromUrl, ToUrl]) ->
  reverse_mpegts:loop(FromUrl, ToUrl);
  
main(_) ->
  io:format("http://[source.url/stream.ts] http://[erlyvideo.url]/stream/[name].ts ~n").

  
