#!/usr/bin/env escript
%%! 


main([FileName]) ->
  Root = filename:join(filename:dirname(escript:script_name()), "..")++"/",
  true = code:add_pathz(Root ++ "ebin"),
  true = code:add_pathz(Root ++ "deps/rtmp/ebin"),
  true = code:add_pathz(Root ++ "deps/log4erl/ebin"),
  true = code:add_pathz(Root ++ "deps/erlmedia/ebin"),
  application:start(log4erl),
  rtmp_dump:run(FileName);
  
main(_) ->
  io:format("CommandsPath ~n").
