#!/usr/bin/env escript
%%! 


main([ListenPort, ForwardAddr]) ->
  Root = filename:join(filename:dirname(escript:script_name()), "..")++"/",
  true = code:add_pathz(Root ++ "ebin"),
  true = code:add_pathz(Root ++ "deps/rtmp/ebin"),
  true = code:add_pathz(Root ++ "deps/log4erl/ebin"),
  true = code:add_pathz(Root ++ "deps/amf/ebin"),
  true = code:add_pathz(Root ++ "deps/erlmedia/ebin"),
  application:start(log4erl),
  application:start(rtmp),
  rtmp_proxy:run(list_to_integer(ListenPort), ForwardAddr),
  init:stop();
  
main(_) ->
  io:format("CommandsPath ~n").
