#!/usr/bin/env escript
%%! 


main([ListenPort, Forward]) ->
  Root = filename:join(filename:dirname(escript:script_name()), ".."),
  [code:add_pathz(Path) || Path <- filelib:wildcard(Root ++ "/apps/*/ebin")],
  application:start(log4erl),
  application:start(rtmp),
  {ok, Pid} = rtmp_proxy:run(list_to_integer(ListenPort), Forward),
  erlang:monitor(process, Pid),
  receive
    {'DOWN', _, process, Pid, _Reason} -> ok
  end,
  ok;
  
main(_) ->
  io:format("ListenPort ForwardHost ~n").
