#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin -pa deps/amf/ebin -pa deps/rtmp/ebin -pa deps/erlmedia/ebin
-mode(compile).

main([]) ->
  io:format("rtmp_publish path url~n"),
  ok;

main([Path, URL]) ->
  application:start(rtmp),
  {ok, Pid} = rtmp_publish:start_link(Path, URL),
  erlang:monitor(process, Pid),
  receive
    {'DOWN', _Ref, process, Pid, _Reason} -> ok
  end.
  

