#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -name reverse_mpegts -mnesia debug verbose -pa ebin -pa deps


main(Command) ->
  Root = filename:join(filename:dirname(escript:script_name()), "..")++"/",
  code:add_pathz(Root ++ "ebin"),
  code:add_pathz(Root ++ "deps/rtmp/ebin"),
  code:add_pathz(Root ++ "deps/log4erl/ebin"),
  code:add_pathz(Root ++ "deps/amf/ebin"),
  code:add_pathz(Root ++ "deps/rtp/ebin"),
  code:add_pathz(Root ++ "deps/rtsp/ebin"),
  code:add_pathz(Root ++ "deps/erlmedia/ebin"),
  rtsp:start(),
  ems:rebuild(),
  run_command(Command).
  
run_command(["capture_camera", Name, URL]) ->
  rtsp_test_client:capture_camera(Name, URL);

run_command(["simulate_camera", Name, Port]) ->
  rtsp_test_client:simulate_camera(Name, list_to_integer(Port));
  
run_command(_) ->
  io:format("ZZZZ ~n").

  
