#!/usr/bin/env ERL_LIBS=apps escript

-include_lib("erlmedia/include/video_frame.hrl").

main([URL]) ->
  application:start(log4erl),
  ems_log:start(),
  application:start(rtsp),
  {ok, RTSP, MediaInfo} = rtsp_socket:read(URL, [{consumer,self()}]),
  erlang:monitor(process, RTSP),
  loop(RTSP).


loop(RTSP) ->
  receive
    #video_frame{} = F -> 
      io:format("~p ~p ~p~n", [F#video_frame.codec, F#video_frame.flavor, round(F#video_frame.dts)]),
      loop(RTSP);
    Else ->
      io:format("Message: ~p~n", [Else])
  end.
