#!/usr/bin/env escript

main([Path, Dir]) ->
  Root = filename:join(filename:dirname(escript:script_name()), "..")++"/",
  [code:add_patha(CodePath) || CodePath <- filelib:wildcard(Root ++ "/apps/*/ebin")],
  [code:add_patha(CodePath) || CodePath <- filelib:wildcard(Root++"../commercial/apps/*/ebin")],
  application:start(log4erl),
  ems_license_client:load(),
  hls_segmenter:segmentize(Path, Dir).
  