#!/bin/bash

Package()
{
echo $1
cd $1
dpkg-scanpackages -m binary > binary/Packages
dpkg-scansources source > source/Sources
gzip -9c binary/Packages > binary/Packages.gz
gzip -c source/Sources > source/Sources.gz

Sign binary Packages
Sign source Sources

}

Sign() {
cd $1
echo "Origin: Erlyvideo repositories
Label: Erlyvideo
Archive: stable
Architectures: i386 amd64 all source
Components: net
Suite: binary
Version: 9.10
Description: Erlyvideo streaming server http://erlyvideo.org/
MD5Sum:" > Release

#ls Packages* Sources* Release | while read ln
ls $2* Release | while read ln
do
md=`md5sum $ln |awk {' print $1 '}`
sz=`du -sb $ln`
echo " $md $sz" >> Release.tmp
done
cat Release.tmp >> Release
rm -f Release.tmp

rm -f Release.gpg
gpg -sbao Release.gpg Release
cd ..
}

Package /apps/erlyvideo/debian/public
Package /apps/erlyvideo/debian/closed

