{application, mpegts,
[{description, "MPEG-TS handling library"},
 {vsn, "0.1"},
 {modules, [ems_http_mpegts,
 iphone_streams,
 mpeg2_crc32,
 mpegts,
 mpegts_file_reader,
 mpegts_play,
 mpegts_reader,
 mpegts_sup]},
 {registered,[mpegts]},
 {applications, [kernel,stdlib]},
 {mod, {mpegts_sup,[]}}
]}.
