{application,meeting,
             [{description,"Base files required for conference"},
              {vsn,"v2.10.2"},
              {id,"meeting"},
              {registered,[]},
              {applications,[erlyvideo]},
              {mod,{meeting_sup,[]}},
              {env,[]},
              {modules,[apps_meeting,meeting_player,meeting_saver,
                        meeting_sup]}]}.
