-define(FILE_CACHE_TIME, 20000).

-record(media_info, {
  host,
  type = undefined,
  device = undefined,
  socket = undefined,
  header = undefined,
  name = undefined,
  path = undefined,
  life_timeout = ?FILE_CACHE_TIME,
  life_timer = undefined,
  options,
  mode,
  demuxer,
  byte_counter = 0,
  filter,
  format,
  width,
  height,
  duration,
  framerate,
  timescale,
  seconds,
  audio_codec = aac,
  video_codec = avc,
  video_config,
  audio_config,
  video_decoder,
  audio_track,
  video_track,
  timeshift,
  shift,
  timeshift_module = ets_timeshift,
	frames = undefined,
	owner = undefined,
	clients = [],
	ts_delta, % Last seen DTS - new TS on restarted stream
	last_dts,
	gop = []
}).
