#!/bin/sh
ERL="erl +A 4 +K true -noinput -noshell"
APP_NAME=ems
NODE_NAME=$APP_NAME@`hostname`
APP_PATH=/usr/lib/erlyvideo
MNESIA_DATA=/var/lib/erlyvideo/mnesia-data

cd $APP_PATH
export HOME=/var/lib/erlyvideo
DEPS=""
for i in $APP_PATH/deps/*/ebin ; do
  DEPS="$DEPS -pa $i "
done
cd /var/lib/erlyvideo
chpst -u erlyvideo -e /etc/service/erlyvideo/config $ERL -pa $APP_PATH/ebin $DEPS -boot start_sasl -s $APP_NAME -mnesia dir "\"${MNESIA_DATA}\"" -name $NODE_NAME

